### ISSUE TITLE
Adding "flair" as a filter

### ISSUE THREAD

**Issue by netstx** [RafhaanShah/Reddit-Post-Notifier#1]
@RafhaanShah Thanks for sharing this project, it works great. I am wondering what you think would be the easiest way to integrate a flair filter for the new post notifications.

**Comment by RafhaanShah** [comment]
Hey, each `submission` has a `link_flair_text` as explained [here](https://www.reddit.com/r/redditdev/comments/dg614p/get_post_flair/) which you could use to to see if it matches whatever filter you're looking for?

**Comment by netstx** [comment]
Thanks, I will see which function would work best to try this in.

**Comment by netstx** [comment]
I added the flair check inside process_submission(), so that has worked for me. Thanks for your help.

**Comment by RafhaanShah** [comment]
Hey sorry I didn't get an email for your last mention, `process_submission` would be the best place to put it. Feel free to make a pull request with your changes if you like!

**Comment by netstx** [comment]
@RafhaanShah no worries! I can definitely submit a PR, but I think I will need make it a bit cleaner first, like add the flairs to filter for as a variable in config first, then add a couple of checks similar to the title keywords, that way it can be done in the config file rather than in app.py.

**Comment by RafhaanShah** [comment]
Cool! Maybe have an extra **optional** key in the config for just flairs? That way existing configurations won't be affected, so something like:

```
  subreddits:
    gamedeals:
      - 'free'

  flairs:
    some_subreddit:
      - 'some_flair'
```

**Comment by netstx** [comment]
That's kind of what I had in mind! I will take a look at how you implemented the config check and will try and make it similar for flairs, just might take me a bit because I don't program in Python very often.
